CREATE TABLE T_MOTTU_MOTO (
                              ID_MOTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              DS_PLACA VARCHAR2(20) UNIQUE NOT NULL,
                              NM_MODELO VARCHAR2(100) NOT NULL,
                              ID_AREA NUMBER NOT NULL,
                              CONSTRAINT FK_MOTO_AREA FOREIGN KEY (ID_AREA) REFERENCES T_MOTTU_AREA(ID_AREA)
);
