INSERT INTO T_MOTTU_AREA (NM_AREA) VALUES ('Centro');
INSERT INTO T_MOTTU_AREA (NM_AREA) VALUES ('Zona Norte');
INSERT INTO T_MOTTU_AREA (NM_AREA) VALUES ('Zona Sul');
INSERT INTO T_MOTTU_AREA (NM_AREA) VALUES ('Zona Leste');
INSERT INTO T_MOTTU_AREA (NM_AREA) VALUES ('Zona Oeste');